package com.jhiptut.third.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TodoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTodoAllPropertiesEquals(Todo expected, Todo actual) {
        assertTodoAutoGeneratedPropertiesEquals(expected, actual);
        assertTodoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTodoAllUpdatablePropertiesEquals(Todo expected, Todo actual) {
        assertTodoUpdatableFieldsEquals(expected, actual);
        assertTodoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTodoAutoGeneratedPropertiesEquals(Todo expected, Todo actual) {
        assertThat(expected)
            .as("Verify Todo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTodoUpdatableFieldsEquals(Todo expected, Todo actual) {
        assertThat(expected)
            .as("Verify Todo relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTodoUpdatableRelationshipsEquals(Todo expected, Todo actual) {}
}
